## Read,write and save Image Using OpenCV In Python

Syntax: cv2.imread(path, flag)

flag: default value is cv2.IMREAD_COLOR
    
Parameters:

cv2.IMREAD_COLOR or 1: reads the image with RGB colors

cv2.IMREAD_GRAYSCALE or 0: reads the image with gray colors

cv2.IMREAD_UNCHANGED or -1: It reads the image as is from the source. If the source image is an RGB, it loads the image into an array with Red, Green, and Blue channels. If the source image is ARGB, it loads the image with three color components along with the alpha or transparency channel.

### Read Image in RGB format

In [9]:
#import opencv packages and other necessory laibraries
import cv2

import numpy as np
import os

In [3]:
path = "boxrobot.jpg" 
 
img = cv2.imread(path, 1) #read image in RGB format
 
print(img.shape)#print shape of image
print(img) #print image array
 
cv2.imshow('image', img) #show image
cv2.waitKey(0) #wait to close image window
 
cv2.destroyAllWindows() #cloase all windows

(1080, 1920, 3)
[[[ 0 68 64]
  [ 0 66 65]
  [ 5 67 67]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 [[ 0 66 64]
  [ 0 65 64]
  [ 2 64 64]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 [[ 0 63 62]
  [ 0 63 62]
  [ 1 61 61]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 ...

 [[ 0 22 26]
  [ 0 22 26]
  [ 0 23 27]
  ...
  [11 67 86]
  [12 65 85]
  [11 64 84]]

 [[ 0 23 27]
  [ 0 23 27]
  [ 0 24 28]
  ...
  [ 5 56 76]
  [ 2 52 72]
  [ 0 49 69]]

 [[ 0 24 28]
  [ 0 24 28]
  [ 1 26 30]
  ...
  [ 0 49 69]
  [ 0 41 62]
  [ 0 37 58]]]


### Read Image in Grey Format

In [4]:
path = "boxrobot.jpg" 
 
img = cv2.imread(path, 0) #read image in RGB format
 
print(img.shape)#print shape of image
print(img) #print image array
 
cv2.imshow('image', img) #show image
cv2.waitKey(0) #wait to close image window
 
cv2.destroyAllWindows() #cloase all windows

(1080, 1920)
[[58 58 60 ...  4  4  4]
 [57 57 57 ...  4  4  4]
 [55 55 54 ...  4  4  4]
 ...
 [20 20 21 ... 66 65 64]
 [21 21 22 ... 56 52 49]
 [22 22 24 ... 49 42 38]]


### Read Image in Alpha or Transference Format

In [5]:
path = "boxrobot.jpg" 
 
img = cv2.imread(path, -1) #read image in RGB format
 
print(img.shape)#print shape of image
print(img) #print image array
 
cv2.imshow('image', img) #show image
cv2.waitKey(0) #wait to close image window
 
cv2.destroyAllWindows() #cloase all windows

(1080, 1920, 3)
[[[ 0 68 64]
  [ 0 66 65]
  [ 5 67 67]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 [[ 0 66 64]
  [ 0 65 64]
  [ 2 64 64]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 [[ 0 63 62]
  [ 0 63 62]
  [ 1 61 61]
  ...
  [ 0  4  5]
  [ 0  4  5]
  [ 0  4  5]]

 ...

 [[ 0 22 26]
  [ 0 22 26]
  [ 0 23 27]
  ...
  [11 67 86]
  [12 65 85]
  [11 64 84]]

 [[ 0 23 27]
  [ 0 23 27]
  [ 0 24 28]
  ...
  [ 5 56 76]
  [ 2 52 72]
  [ 0 49 69]]

 [[ 0 24 28]
  [ 0 24 28]
  [ 1 26 30]
  ...
  [ 0 49 69]
  [ 0 41 62]
  [ 0 37 58]]]


### Read Image from Full Image Path

In [7]:
path = r"C:\Users\Acer\Downloads\boxrobo.jpg" 
 
img = cv2.imread(path, 1) #read image in RGB format
 
print(img.shape)#print shape of image
print(img) #print image array
 
cv2.imshow('image', img) #show image
cv2.waitKey(0) #wait to close image window
 
cv2.destroyAllWindows() #cloase all windows

(900, 1440, 3)
[[[ 33  33  51]
  [ 33  33  51]
  [ 33  33  51]
  ...
  [ 79  71  71]
  [ 78  70  70]
  [ 77  69  69]]

 [[ 33  33  51]
  [ 33  33  51]
  [ 33  33  51]
  ...
  [ 79  71  71]
  [ 78  70  70]
  [ 78  70  70]]

 [[ 34  34  52]
  [ 34  34  52]
  [ 34  34  52]
  ...
  [ 77  72  71]
  [ 77  72  71]
  [ 76  71  70]]

 ...

 [[ 48 118  95]
  [ 48 118  95]
  [ 50 118  95]
  ...
  [ 51 109  91]
  [ 53 108  91]
  [ 54 109  92]]

 [[ 46 116  93]
  [ 46 116  93]
  [ 48 116  93]
  ...
  [ 49 107  89]
  [ 51 106  89]
  [ 52 107  90]]

 [[ 44 114  91]
  [ 44 114  91]
  [ 47 115  92]
  ...
  [ 48 106  88]
  [ 50 105  88]
  [ 50 105  88]]]


### Show Numpy array as Image

In [8]:
import numpy as np
 
matx = np.zeros((200,200)) # numpy array with width =200, height=200
 
cv2.imshow("Zeros matx", matx) # show numpy array
 
cv2.waitKey(0) # wait for ay key to exit window
cv2.destroyAllWindows() # close all windows

### Save Numpy Array

In [10]:

 
rand_array = np.random.randint(255, size = (300,600,3))
 
cv2.imwrite("rand_np_array.png", rand_array) # imwrite(filename, img[, params])
 
img = cv2.imread("rand_np_array.png")
cv2.imshow('image', img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Save Images from Video

In [ ]:
video_path = r"C:\Users\kashz\AI Life\AI Projects - IAIP, PTs (Web + Channel)\02 OpenCV\007 Live Face and Eye Detection\school_girl.mp4"
 
os.mkdir("video_to_image") # create directory
 
cap = cv2.VideoCapture(video_path) # capture video
 
img_count = 1
while cap.isOpened():
    ret, frame = cap.read() # read video frame
     
    if not ret:
        print("Unable to read frame")
        break
     
    is_img_write = cv2.imwrite(f"video_to_image\image{img_count}.jpeg", frame)
     
    if is_img_write:
        print(f'image save at video_to_image\image{img_count}.jpeg')
         
    cv2.imshow("video", frame )
     
    cv2.waitKey(25) &amp; 0xff == ord('q')
    img_count += 1
     
cap.release()
cv2.destroyAllWindows()